// Database di base, scritto per HealthFit. Valori medi per 100 g di parte edibile
// (arrotondati, da tabelle nutrizionali pubbliche). `g` = porzione tipica in grammi.
const F = (id, name, kcal, p, c, f, g = 100, cat = '') => ({ id, name, kcal, p, c, f, g, cat });

export const FOODS = [
  F('pane', 'Pane comune', 270, 8.5, 55, 1.2, 50, 'Cereali'),
  F('pane-int', 'Pane integrale', 245, 9, 45, 2.5, 50, 'Cereali'),
  F('pasta', 'Pasta di semola (cruda)', 355, 12.5, 72, 1.5, 80, 'Cereali'),
  F('pasta-int', 'Pasta integrale (cruda)', 340, 13.5, 66, 2.5, 80, 'Cereali'),
  F('riso', 'Riso bianco (crudo)', 355, 7, 79, 0.6, 80, 'Cereali'),
  F('riso-basmati', 'Riso basmati (crudo)', 350, 8, 77, 0.8, 80, 'Cereali'),
  F('avena', 'Fiocchi d\'avena', 370, 13, 60, 7, 40, 'Cereali'),
  F('cornflakes', 'Corn flakes', 375, 7, 84, 0.9, 30, 'Cereali'),
  F('fette', 'Fette biscottate', 405, 11, 75, 6, 10, 'Cereali'),
  F('gallette', 'Gallette di riso', 385, 8, 81, 3, 9, 'Cereali'),
  F('patate', 'Patate', 80, 2, 18, 0.1, 200, 'Verdure'),
  F('pizza', 'Pizza margherita', 255, 11, 33, 9, 300, 'Piatti'),
  F('lasagne', 'Lasagne alla bolognese', 165, 9, 14, 8, 300, 'Piatti'),
  F('pollo', 'Petto di pollo (crudo)', 105, 23, 0, 1.2, 150, 'Carne e pesce'),
  F('tacchino', 'Fesa di tacchino (cruda)', 107, 24, 0, 1, 150, 'Carne e pesce'),
  F('manzo', 'Manzo magro (crudo)', 130, 21, 0, 5, 150, 'Carne e pesce'),
  F('macinato', 'Macinato di manzo 10%', 175, 20, 0, 10, 120, 'Carne e pesce'),
  F('maiale', 'Lonza di maiale (cruda)', 145, 21, 0, 6.5, 150, 'Carne e pesce'),
  F('prosciutto-cotto', 'Prosciutto cotto', 140, 19, 1, 7, 50, 'Carne e pesce'),
  F('prosciutto-crudo', 'Prosciutto crudo', 250, 26, 0, 16, 50, 'Carne e pesce'),
  F('bresaola', 'Bresaola', 155, 33, 0, 2, 50, 'Carne e pesce'),
  F('salmone', 'Salmone (crudo)', 185, 20, 0, 12, 150, 'Carne e pesce'),
  F('tonno-nat', 'Tonno al naturale (sgocciolato)', 105, 25, 0, 0.8, 80, 'Carne e pesce'),
  F('tonno-olio', 'Tonno sott\'olio (sgocciolato)', 190, 25, 0, 10, 80, 'Carne e pesce'),
  F('merluzzo', 'Merluzzo (crudo)', 75, 17, 0, 0.5, 150, 'Carne e pesce'),
  F('gamberi', 'Gamberi (crudi)', 75, 17, 0.5, 0.6, 120, 'Carne e pesce'),
  F('uova', 'Uovo intero', 130, 12.5, 0.5, 9, 60, 'Uova e latticini'),
  F('albume', 'Albume', 45, 11, 0.7, 0.2, 100, 'Uova e latticini'),
  F('latte-ps', 'Latte parzialmente scremato', 46, 3.3, 5, 1.6, 200, 'Uova e latticini'),
  F('latte-int', 'Latte intero', 64, 3.3, 4.9, 3.6, 200, 'Uova e latticini'),
  F('yogurt-greco', 'Yogurt greco 0%', 57, 10, 4, 0.2, 170, 'Uova e latticini'),
  F('yogurt-bianco', 'Yogurt bianco intero', 65, 3.8, 4.5, 3.5, 125, 'Uova e latticini'),
  F('mozzarella', 'Mozzarella', 250, 18, 1, 19, 125, 'Uova e latticini'),
  F('parmigiano', 'Parmigiano', 390, 33, 0, 28, 20, 'Uova e latticini'),
  F('ricotta', 'Ricotta vaccina', 145, 9, 3.5, 11, 100, 'Uova e latticini'),
  F('fiocchi-latte', 'Fiocchi di latte', 100, 12, 3, 4.5, 150, 'Uova e latticini'),
  F('lenticchie', 'Lenticchie secche', 325, 23, 51, 2.5, 70, 'Legumi'),
  F('ceci', 'Ceci in scatola (sgocciolati)', 120, 7, 16, 2.5, 120, 'Legumi'),
  F('fagioli', 'Fagioli borlotti in scatola', 95, 6.5, 14, 0.5, 120, 'Legumi'),
  F('tofu', 'Tofu', 120, 13, 1.5, 7, 100, 'Legumi'),
  F('mela', 'Mela', 52, 0.3, 14, 0.2, 180, 'Frutta'),
  F('banana', 'Banana', 90, 1.1, 22, 0.3, 120, 'Frutta'),
  F('arancia', 'Arancia', 45, 0.9, 11, 0.2, 180, 'Frutta'),
  F('fragole', 'Fragole', 32, 0.7, 7.7, 0.3, 150, 'Frutta'),
  F('kiwi', 'Kiwi', 60, 1.1, 14, 0.5, 80, 'Frutta'),
  F('mirtilli', 'Mirtilli', 57, 0.7, 14, 0.3, 100, 'Frutta'),
  F('avocado', 'Avocado', 160, 2, 8.5, 15, 100, 'Frutta'),
  F('insalata', 'Insalata mista', 18, 1.4, 3, 0.2, 100, 'Verdure'),
  F('pomodori', 'Pomodori', 18, 0.9, 3.9, 0.2, 150, 'Verdure'),
  F('zucchine', 'Zucchine', 17, 1.2, 3, 0.3, 200, 'Verdure'),
  F('broccoli', 'Broccoli', 34, 2.8, 7, 0.4, 200, 'Verdure'),
  F('spinaci', 'Spinaci', 23, 2.9, 3.6, 0.4, 200, 'Verdure'),
  F('carote', 'Carote', 41, 0.9, 10, 0.2, 100, 'Verdure'),
  F('passata', 'Passata di pomodoro', 30, 1.4, 5.5, 0.2, 100, 'Verdure'),
  F('olio', 'Olio extravergine d\'oliva', 900, 0, 0, 100, 10, 'Condimenti'),
  F('burro', 'Burro', 745, 0.8, 0.5, 82, 10, 'Condimenti'),
  F('burro-arachidi', 'Burro di arachidi', 590, 25, 16, 50, 20, 'Condimenti'),
  F('miele', 'Miele', 305, 0.3, 82, 0, 15, 'Condimenti'),
  F('zucchero', 'Zucchero', 400, 0, 100, 0, 5, 'Condimenti'),
  F('marmellata', 'Marmellata', 240, 0.4, 59, 0.1, 20, 'Condimenti'),
  F('mandorle', 'Mandorle', 600, 21, 9, 52, 30, 'Frutta secca'),
  F('noci', 'Noci', 680, 15, 7, 65, 30, 'Frutta secca'),
  F('cioccolato', 'Cioccolato fondente 70%', 580, 8, 33, 43, 20, 'Snack'),
  F('biscotti', 'Biscotti frollini', 470, 6.5, 70, 18, 30, 'Snack'),
  F('cornetto', 'Cornetto semplice', 410, 7.5, 47, 21, 50, 'Snack'),
  F('gelato', 'Gelato alla crema', 215, 4, 24, 12, 100, 'Snack'),
  F('whey', 'Proteine whey in polvere', 380, 78, 7, 5, 30, 'Integratori'),
  F('barretta', 'Barretta proteica', 360, 33, 35, 12, 50, 'Integratori'),
  F('caffe', 'Caffè espresso', 2, 0.1, 0.3, 0, 30, 'Bevande'),
  F('succo', 'Succo d\'arancia', 45, 0.7, 10, 0.2, 200, 'Bevande'),
  F('birra', 'Birra', 43, 0.5, 3.5, 0, 330, 'Bevande'),
  F('vino', 'Vino rosso', 85, 0.1, 2.6, 0, 125, 'Bevande'),
  F('cola', 'Bibita tipo cola', 42, 0, 10.6, 0, 330, 'Bevande'),
];

export const MEALS = [
  { id: 'colazione', label: 'Colazione' },
  { id: 'pranzo', label: 'Pranzo' },
  { id: 'cena', label: 'Cena' },
  { id: 'spuntini', label: 'Spuntini' },
];

export const MUSCLES = ['Petto', 'Schiena', 'Gambe', 'Spalle', 'Braccia', 'Core', 'Cardio'];

const E = (name, muscle, equip) => ({ name, muscle, equip });
export const EXERCISES = [
  E('Panca piana con bilanciere', 'Petto', 'Bilanciere'),
  E('Panca inclinata con manubri', 'Petto', 'Manubri'),
  E('Croci ai cavi', 'Petto', 'Cavi'),
  E('Chest press', 'Petto', 'Macchina'),
  E('Piegamenti', 'Petto', 'Corpo libero'),
  E('Dip alle parallele', 'Petto', 'Corpo libero'),
  E('Trazioni alla sbarra', 'Schiena', 'Corpo libero'),
  E('Lat machine', 'Schiena', 'Cavi'),
  E('Rematore con bilanciere', 'Schiena', 'Bilanciere'),
  E('Rematore con manubrio', 'Schiena', 'Manubri'),
  E('Pulley basso', 'Schiena', 'Cavi'),
  E('Stacco da terra', 'Schiena', 'Bilanciere'),
  E('Squat con bilanciere', 'Gambe', 'Bilanciere'),
  E('Leg press', 'Gambe', 'Macchina'),
  E('Affondi con manubri', 'Gambe', 'Manubri'),
  E('Stacco rumeno', 'Gambe', 'Bilanciere'),
  E('Leg extension', 'Gambe', 'Macchina'),
  E('Leg curl', 'Gambe', 'Macchina'),
  E('Hip thrust', 'Gambe', 'Bilanciere'),
  E('Calf raise', 'Gambe', 'Macchina'),
  E('Lento avanti con bilanciere', 'Spalle', 'Bilanciere'),
  E('Shoulder press con manubri', 'Spalle', 'Manubri'),
  E('Alzate laterali', 'Spalle', 'Manubri'),
  E('Face pull', 'Spalle', 'Cavi'),
  E('Curl con bilanciere', 'Braccia', 'Bilanciere'),
  E('Curl con manubri', 'Braccia', 'Manubri'),
  E('Curl a martello', 'Braccia', 'Manubri'),
  E('Push down ai cavi', 'Braccia', 'Cavi'),
  E('French press', 'Braccia', 'Bilanciere'),
  E('Plank', 'Core', 'Corpo libero'),
  E('Crunch', 'Core', 'Corpo libero'),
  E('Russian twist', 'Core', 'Corpo libero'),
  E('Ab wheel', 'Core', 'Attrezzo'),
  E('Vogatore', 'Cardio', 'Macchina'),
  E('Cyclette', 'Cardio', 'Macchina'),
];

// Attività cardio per il diario, con MET di riferimento
export const CARDIO = [
  { id: 'camminata', name: 'Camminata (5 km/h)', met: 3.5 },
  { id: 'camminata-veloce', name: 'Camminata veloce (6,5 km/h)', met: 5 },
  { id: 'corsa-lenta', name: 'Corsa lenta (8 km/h)', met: 8.3 },
  { id: 'corsa', name: 'Corsa (10 km/h)', met: 9.8 },
  { id: 'corsa-veloce', name: 'Corsa veloce (12 km/h)', met: 11.8 },
  { id: 'bici', name: 'Bicicletta (moderata)', met: 7.5 },
  { id: 'cyclette', name: 'Cyclette (moderata)', met: 6.8 },
  { id: 'nuoto', name: 'Nuoto (moderato)', met: 7 },
  { id: 'ellittica', name: 'Ellittica', met: 5 },
  { id: 'vogatore', name: 'Vogatore (moderato)', met: 7 },
  { id: 'hiit', name: 'HIIT / circuito', met: 8 },
  { id: 'yoga', name: 'Yoga', met: 2.5 },
  { id: 'calcio', name: 'Calcio / calcetto', met: 7 },
  { id: 'tennis', name: 'Tennis / padel', met: 7 },
  { id: 'ballo', name: 'Ballo', met: 5 },
];

export const DEFAULT_ROUTINES = [
  { id: 'r-push', name: 'Push (spinta)', exercises: [
    { name: 'Panca piana con bilanciere', sets: 4, reps: 8 },
    { name: 'Shoulder press con manubri', sets: 3, reps: 10 },
    { name: 'Panca inclinata con manubri', sets: 3, reps: 10 },
    { name: 'Alzate laterali', sets: 3, reps: 15 },
    { name: 'Push down ai cavi', sets: 3, reps: 12 },
  ] },
  { id: 'r-pull', name: 'Pull (tirata)', exercises: [
    { name: 'Trazioni alla sbarra', sets: 4, reps: 6 },
    { name: 'Rematore con bilanciere', sets: 4, reps: 8 },
    { name: 'Lat machine', sets: 3, reps: 10 },
    { name: 'Face pull', sets: 3, reps: 15 },
    { name: 'Curl con manubri', sets: 3, reps: 12 },
  ] },
  { id: 'r-legs', name: 'Gambe', exercises: [
    { name: 'Squat con bilanciere', sets: 4, reps: 6 },
    { name: 'Stacco rumeno', sets: 3, reps: 8 },
    { name: 'Leg press', sets: 3, reps: 12 },
    { name: 'Leg curl', sets: 3, reps: 12 },
    { name: 'Calf raise', sets: 4, reps: 15 },
  ] },
];
